#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Kimai.Resource", IsApplication=true)]

namespace Kimai
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001a
			public const int SCROLLER_ID = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int TEXT_STATUS_ID = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int TimerView = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int apiUserNme = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int author_name = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int btn_cancel = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int btn_save = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int btn_sqlcancel = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int btn_view_data = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int editComments = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int edit_password = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int edit_url = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int edit_username = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int lbl_password = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int lbl_title = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int lbl_url = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int lbl_username = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06001d
			public const int menu_about = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int menu_exit = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int menu_refresh = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int menu_settings = 2131099676;
			
			// aapt resource value: 0x7f06000a
			public const int spinnerActivities = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int spinnerCustomers = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int spinnerProjects = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int status_message = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int textView1 = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int toggleButton1 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int update = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int versionInfo = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SqlLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int option_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_autorenew = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_copy = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_cut = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_paste = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_create = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_settings = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int author_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int code_name = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
