#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TimeTracker.Resource", IsApplication=true)]

namespace TimeTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int accent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int primary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primaryDark = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int splash_background = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int window_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int KimaiDroid = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash_screen = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int apiUserNme = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int btn_clear = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int btn_main = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int btn_settings = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int btn_start = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int btn_stop = 2131230723;
			
			// aapt resource value: 0x7f08000c
			public const int edit_password = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int edit_url = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int edit_username = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int lbl_password = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int lbl_title = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int lbl_url = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int lbl_username = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
